### PR TITLE
Reformat the repo to be more Python and more Github

### PR DESCRIPTION
**Pull request by EntropyIncreaser**
changed some case, file tree system and code style. added the `gitignore` system

### CODE REVIEW

**Comment by Cynthia7979** [comment]
Why use 8-letters-indent?

**Comment by EntropyIncreaser** [comment]
@Cynthia7979 Not 8-letters, but tab! It's better to use tab cuz it could be resized by your editor

**Comment by Cynthia7979** [comment]
@EntropyIncreaser  Okay and how to merge branches?

**Comment by EntropyIncreaser** [comment]
@Cynthia7979 Find a button called `Merge`.

**Comment by Cynthia7979** [comment]
Sorry where is merge TAT

**Comment by EntropyIncreaser** [comment]
@Cynthia7979  
img

**Comment by Cynthia7979** [comment]
OH ok

**Comment by Cynthia7979** [comment]
Finished

**Comment by EntropyIncreaser** [comment]
@Cynthia7979 So why still open?

**Comment by Cynthia7979** [comment]
I'll try again, so I merge and close it right?

**Comment by EntropyIncreaser** [comment]
@Cynthia7979 right

**Comment by Cynthia7979** [comment]
Okay that's really finished

**Comment by EntropyIncreaser** [comment]
@Cynthia7979 I realized that this pull request is useless when you rebuilt the file system...

**Comment by EntropyIncreaser** [comment]
@Cynthia7979 So u may should redo the merge? I guess u should use the <kbd>git</kbd> command line tool to fix this.

**Comment by Cynthia7979** [comment]
I already downloaded Git and learned how to use it

**Pull request merged**
